1 sem/Web-technology/QuestionDay/question_day/urls.py
from django.conf.urls import url
from django.contrib import admin
from ask import views

app_name = 'ask'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^vote/$', views.vote, name='vote'),
    url(r'^correct/$', views.correct, name='correct'),
    url(r'^tag/(?P<tag_name>[\w#.+-]+)/', views.bytag, name='bytag'),
    url(r'^question/(?P<question_id>[0-9]+)/', views.question, name='question'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^ask/', views.ask, name='ask'),
    url(r'^hot/', views.hot, name='hot'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^signup_success/', views.signup_success, name='signup_success'),
    url(r'^/?', views.index, name='index'),
]

1 sem/Web-technology/QuestionDay/ask/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.http import Http404
from django.db.models import Count
import requests
import json


class QuestionManager(models.Manager):
    def get_question_by_id(self, q_id):
        try:
            q = self.get(pk=q_id)
            q.tag_list = self.get_tags_for_question_by_id(q.id)
            q.answers_count = self.get_count_of_answers(q.id)
        except Question.DoesNotExist:
            q = None
            raise Http404("Question does not exist")
        return q

    def get_new_questions(self):
        q_list = self.prefetch_related('user').order_by('-pub_date')[:100]
        return Question.objects.fill_questions(q_list)

    def get_best_questions(self):
        q_list = self.order_by('-rating')[:100]
        return Question.objects.fill_questions(q_list)

    def get_count_of_answers(self, q_id):
        return AnswerManager.get_count_of_answers_for_question(Answer.objects, q_id)

    def get_answers_for_question_by_id(self, q_id):
        return AnswerManager.get_answers_for_question_by_id(Answer.objects, q_id)

    def get_tags_for_question_by_id(self, q_id):
        return TagManager.get_tags_for_question_by_id(Tag.objects, q_id)

    def get_questions_by_tagname(self, tag_name):
        q_list = self.filter(tag__name=tag_name)
        return Question.objects.fill_questions(q_list)

    def fill_questions(self, q_list):
        for q in q_list:
            q.tag_list = self.get_tags_for_question_by_id(q.id)
            q.answers_count = self.get_count_of_answers(q.id)
        return q_list


class AnswerManager(models.Manager):
    def str_to_bool(self, s):
        if s == 'true':
            return True
        elif s == 'false':
            return False
        else:
            raise ValueError

    def get_count_of_answers_for_question(self, q_id):
        return self.filter(question=q_id).count()

    def get_answers_for_question_by_id(self, q_id):
        return self.filter(question=q_id).order_by('-pub_date')[:100]

    def get_answer_by_id(self, id):
        return self.get(id=id)

    def set_correct(self, value, answer_id):
        a = Answer.objects.get(pk=answer_id)
        a.correct = self.str_to_bool(value)
        a.save()
   

class TagManager(models.Manager):
    def get_tags_for_question_by_id(self, q_id):
        return self.filter(question=q_id)

    def get_popular_tags(self):
        return self.annotate(Count('question')).order_by('-question__count')[:10]

    def get_tag_by_name(self, tag_name):
        return self.get(name=tag_name)


class ProfileManager(models.Manager):
    def get_popular_users(self):
        return self.annotate(Count('question')).order_by('-question__count')[:10]

    def check_user_unicue(self, login):
        return User.objects.filter(username=login).exists()

    def get_profile_by_user(self, user_id):
        return self.get(user=user_id)


class LikeManager(models.Manager):
    def str_to_bool(self, s):
        if s == 'True':
            return True
        elif s == 'False':
            return False
        else:
            raise ValueError

    def check_a_like(self, user_id, answer_id):
        try:
            ct = ContentType.objects.get(app_label="ask", model="answer")
            check = self.get(user=user_id, content_type=ct, object_id=answer_id).like
        except Like.DoesNotExist:
            check = None
        return check

    def check_q_like(self, user_id, question_id):
        try:
            ct = ContentType.objects.get(app_label="ask", model="question")
            check = self.get(user=user_id, content_type=ct, object_id=question_id).like
        except Like.DoesNotExist:
            check = None
        return check

    def a_like(self, user_id, answer_id, like0):
        like = self.str_to_bool(like0)
        answer = Answer.objects.get_answer_by_id(answer_id)
        rating = answer.rating

        check = self.check_a_like(user_id, answer_id)
        if check is None:
            ct = ContentType.objects.get(app_label="ask", model="answer")
            l = Like.objects.create(user=user_id, like=like, content_type=ct, object_id=answer_id)
            l.save()
            if like:
                rating += 1
            else:
                rating -= 1
            answer.rating = rating
            answer.save()
            return 'Success', rating
        else:
            if check == like:
                return 'Already', rating
            else:
                ct = ContentType.objects.get(app_label="ask", model="answer")
                l = self.get(user=user_id, content_type=ct, object_id=answer_id)
                l.like = like
                l.save()

                if like == True:
                    rating += 2
                else:
                    rating -= 2
                answer.rating = rating
                answer.save()

                return 'Success', rating

    def q_like(self, user_id, question_id, like0):
        like = self.str_to_bool(like0)
        question = Question.objects.get_question_by_id(question_id)
        rating = question.rating

        check = self.check_q_like(user_id, question_id)
        if check is None:
            ct = ContentType.objects.get(app_label="ask", model="question")
            l = Like.objects.create(user=user_id, like=like, content_type=ct, object_id=question_id)
            l.save()
            if like:
                rating += 1
            else:
                rating -= 1
            question.rating = rating
            question.save()
            return 'Success', rating
        else:
            if check == like:
                return 'Already', rating
            else:
                ct = ContentType.objects.get(app_label="ask", model="question")
                l = self.get(user=user_id, content_type=ct, object_id=question_id)
                l.like = like
                l.save()

                if like:
                    rating += 2
                else:
                    rating -= 2
                question.rating = rating
                question.save()

                return 'Success', rating


# ______________MODELS______________#


class Question(models.Model):
    user = models.ForeignKey('Profile')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField('Tag')
    objects = QuestionManager()

    def __str__(self):
        return "{} {} {} {}".format(self.id, self.title, self.rating, self.pub_date)


class Answer(models.Model):
    user = models.ForeignKey('Profile')
    question = models.ForeignKey('Question')
    text = models.TextField()
    rating = models.IntegerField(default=0)
    correct = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    objects = AnswerManager()

    def notify(self):
        data = {'id': self.id, 'user': self.user.id, 'text': self.text, 'rating': self.rating, 'correct': self.correct, }
        requests.post('http://question-day.io/pub?id=1', data=json.dumps(data))

    def __str__(self):
        return "{} {}".format(self.question.title, self.pub_date)


class Tag(models.Model):
    name = models.CharField(max_length=255)
    objects = TagManager()

    def __str__(self):
        return "{}".format(self.name)


class Profile(models.Model):
    user = models.OneToOneField(User)
    nickname = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='uploads', null=True, blank=True)
    objects = ProfileManager()

    def __str__(self):
        return "{}".format(self.nickname)


class Like(models.Model):
    content_type = models.ForeignKey(ContentType, related_name="content_type_likes")
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    user = models.ForeignKey('Profile')
    like = models.BooleanField()
    objects = LikeManager()

    def __str__(self):
        return "{} {} {} {} {}".format(self.content_type, self.user, self.object_id, self.content_object, self.like)

1 sem/Web-technology/QuestionDay/ask/forms.py
from django import forms
from django.contrib.auth.models import User
from ask.models import Profile, Question, Tag, Answer
from django.contrib.auth import login
import string
from django.contrib.auth import authenticate


class SignUpForm(forms.Form):
    login = forms.CharField(required=True, max_length=100, error_messages={'blank': 'Enter login'},
                            widget=forms.TextInput(attrs={
                                'class': 'form-control custom-input-text',
                                'placeholder': 'Enter login'
                            }))
    email = forms.EmailField(max_length=100, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Enter email'
    }), error_messages={'required': 'Enter email'})
    nickname = forms.CharField(required=True, max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Enter nickname'
    }), error_messages={'required': 'Enter nickname'})
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Enter password'
    }), error_messages={'required': 'Enter password'})

    repeat_password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Repeat password'
    }), error_messages={'required': 'Repeat password'})

    avatar = forms.FileField(required=False, label='Upload avatar', widget=forms.FileInput(attrs={
        'class': 'filestyle',
        'data-icon': 'false',
        'data-placeholder': 'No file',
        'data-buttonBefore': 'true',
    }))

    def clean(self):
        data = self.cleaned_data
        errors = []
        if Profile.objects.check_user_unicue(data['login']):
            msg = 'This login already used'
            self.add_error('login', msg)
            errors.append({'login': msg})
        if len(data['password']) < 8:
            msg = 'Password is too short. 8 is min'
            self.add_error('password', msg)
            errors.append({'password': msg})
        elif data['password'] != data['repeat_password']:
            msg = 'Passwords not equals'
            self.add_error('password', msg)
            self.add_error('repeat_password', msg)
            errors.append({'password': msg})
            # errors.append({'repeat_password': msg})
        if len(errors) != 0:
            raise forms.ValidationError(errors)
        return data

    def create_user(self):
        user = User.objects.create_user(self.cleaned_data['login'], self.cleaned_data['email'],
                                        self.cleaned_data['password'])
        user.save()
        profile = Profile.objects.create(user=user, nickname=self.cleaned_data['nickname'],
                                         avatar=self.cleaned_data['avatar'])
        profile.save()

    def save(self):
        self.create_user()


class AskForm(forms.Form):
    title = forms.CharField(max_length=100, error_messages={'required': 'Fill title'},
                            widget=forms.TextInput(attrs={
                                'class': 'form-control custom-input-text',
                                'placeholder': 'Enter title'
                            }))
    text = forms.CharField(max_length=1000, error_messages={'required': 'Fill text'},
                           widget=forms.Textarea(attrs={
                               'class': 'form-control custom-textarea-text',
                               'placeholder': 'Enter text',
                               'rows': '10',
                           }))

    tags = forms.CharField(max_length=40, error_messages={'required': 'Fill text'},
                           widget=forms.TextInput(attrs={
                               'class': 'form-control custom-input-text',
                               'placeholder': 'Enter tags with spaces'
                           }))

    def save(self, user):
        data = self.cleaned_data
        tags_names = data['tags'].split()
        tags_objects = []
        for tag_name in tags_names:
            lower_tag_name = tag_name.lower()
            try:
                tag = Tag.objects.get_tag_by_name(lower_tag_name)
            except Tag.DoesNotExist:
                tag = None

            if tag is not None:
                tags_objects.append(tag)
            else:
                new_tag = Tag.objects.create(name=tag_name)
                new_tag.save()
                new_tag = Tag.objects.get_tag_by_name(new_tag.name)
                tags_objects.append(new_tag)

        profile = Profile.objects.get(user=user)
        q = Question.objects.create(user=profile, title=data['title'], text=data['text'])
        for tag_object in tags_objects:
            q.tag.add(tag_object)
        q.save()

        return q.id


class AnswerForm(forms.Form):
    answer = forms.CharField(max_length=1000, error_messages={'required': 'Write your answer'},
                             widget=forms.Textarea(attrs={
                                 'class': 'form-control custom-textarea-text',
                                 'placeholder': 'Enter your answer here',
                                 'rows': '10',
                             }))

    def save(self, user, question):
        data = self.cleaned_data
        profile = Profile.objects.get(user=user)
        a = Answer.objects.create(user=profile, question=question, text=data['answer'])
        a.save()
        return a


class EditProfileForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Enter email'
    }), error_messages={'required': 'Enter email'})
    nickname = forms.CharField(required=True, max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control custom-input-text',
        'placeholder': 'Enter nickname'
    }), error_messages={'required': 'Enter nickname'})
    avatar = forms.FileField(required=False, label='Upload avatar', widget=forms.FileInput(attrs={
        'class': 'filestyle',
        'data-icon': 'false',
        'data-placeholder': 'No file',
        'data-buttonBefore': 'true',
    }))

    def save(self, user):
        data = self.cleaned_data
        profile = Profile.objects.get(user=user)
        user = User.objects.get(pk=user.id)

        profile.nickname = data['nickname']
        profile.avatar = data['avatar']
        profile.save()

        user.email = data['email']
        user.save()

1 sem/Web-technology/QuestionDay/templates/ask.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-left">
        <h2 class="custom-title-left">New Question</h2>
        {% for e in form.non_field_errors %}
            <h4 id="error-text" class="custom-text-left custom-text-error">{{ e }}</h4>
        {% endfor %}
        <form method="post" action="{% url 'ask' %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}has-error {% endif %}">
                    <label class="custom-title-left">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% if field.errors %}<p class="help-block custom-text-left">{{ field.errors }}</p>{% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-default custom-button">Ask a question</button>
        </form>
    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ block_title }}</title>

    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

    <link rel="stylesheet" href="/src/css/main/styles.css">

    <link rel="stylesheet" href="/src/css/texts/text.css">
    <link rel="stylesheet" href="/src/css/views/buttons.css">
    <link rel="stylesheet" href="/src/css/views/inputs.css">
    <link rel="stylesheet" href="/vendor/bootstrap/bootstrap.min.css">
</head>
<body class="bg-color">
<div class="container">
    <div class="container-fluid text-center margin-bottom">
        <div class="row">
            <div class="col-sm-12">
                <img src="/src/img/logo.png" class="logo-image" width="100" height="100" alt="logo"
                     onclick="location.href='/'">
                <h4 class="custom-title-center">QUESTION DAY</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
		<div data-spy="affix" data-offset-top="139">
                <div class="card">
                        {% if user.is_authenticated %}
                            <div>
                                <h4 class="custom-title-center">{{ user.profile }}</h4>
                                {% if user.profile.avatar != '' %}
                                    <img src="/{{ user.profile.avatar }}" width="100" height="100" class="img-circle"
                                         alt="avatar">
                                {% else %}
                                    <img src="/src/img/default_avatar.png" width="100" height="100" class="img-circle"
                                         alt="avatar">
                                {% endif %}

                                <a href="{% url 'settings' %}" class="btn custom-button" role="button">Settings</a>
                                <a href="{% url 'logout' %}" class="btn custom-button" role="button">Log Out</a>
                                <a href="{% url 'ask' %}" class="btn custom-button custom-button__important"
                                   role="button">Ask</a>
                            </div>
                        {% else %}
                            {% if get == None %}
                                <a href="{% url 'login' %}?continue={{ request.path }}" class="btn custom-button"
                                   role="button">Log In</a>
                                <a href="{% url 'signup' %}?continue={{ request.path }}" class="btn custom-button"
                                   role="button">Register</a>
                            {% else %}
                                <a href="{% url 'login' %}?continue={{ get }}" class="btn custom-button"
                                   role="button">Log In</a>
                                <a href="{% url 'signup' %}?continue={{ get }}" class="btn custom-button"
                                   role="button">Register</a>
                            {% endif %}
                        {% endif %}
                    </div>
                <div class="card">
                    <h4 class="custom-title-center">Popular Tags</h4>
                    <p class="custom-text-center">
                        {% for tag in popular_tags %}
                                <a href="{% url 'bytag' tag.name %}">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                </div>
                <div class="card">
                    <h4 class="custom-title-center">Best Members</h4>
                    <p class="custom-text-center">
                        {% for user in popular_users %}
                                <a>{{ user.nickname }}</a>
                        {% endfor %}
                    </p>
                </div>
            </div>
	    </div>
            <div class="col-sm-9">
                <div class="card">
                    {%  block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/vendor/jquery/jquery-3.1.0.min.js"></script>
<script type="text/javascript" src="/vendor/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="/vendor/bootstrap/bootstrap-filestyle.min.js"></script>
<script type="text/javascript" src="/src/js/voteing.js"></script>
<script type="text/javascript" src="/src/js/correcting.js"></script>
</body>
</html>

1 sem/Web-technology/QuestionDay/templates/hot.html
{% extends 'base.html' %}
{% block content %}
    <div class="form-group no-margin">
        <input type="text" class="form-control custom-input-text" placeholder="Search"
               maxlength="100">
    </div>
    <div class="card">

        <div>
            <div class="div-align-left">
                <h2 class="custom-title-left text-inline-block">Hot Questions</h2>
            </div>
            <div class="container-fluid text-center">
                {% for question in questions %}
			{% include "question_item.html" %}
                {% endfor %}
            </div>

            {% include "paginator.html" %}
        </div>

    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="form-group no-margin">
        <input type="text" class="form-control custom-input-text" placeholder="Search"
               maxlength="100">
    </div>
    <div class="card">

        <div>
            <div class="div-align-left">
                <h2 class="custom-title-left text-inline-block">New Questions</h2>
                <h3 class="custom-text-left text-inline-block"><a href="{% url 'hot' %}">Hot Questions</a></h3>
            </div>
            <div class="container-fluid text-center">
                {% for question in questions %}
                	{% include "question_item.html" %}
		{% endfor %}
            </div>

             {% include "paginator.html" %}
        </div>

    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-left">
        <h2 class="custom-title-left">Log In</h2>
        <h4 id="error-text" class="custom-text-left custom-text-error">{{ error }}</h4>
        <form class="form-signin" method="post" action="{% url 'login' %}?continue={{ get }}">
            {% csrf_token %}
            <div class="form-group">
                <label for="login" class="custom-title-left">Login:</label>
                <input type="text" class="form-control custom-input-text" id="login" name="login" placeholder="Enter login"
                       maxlength="100">
            </div>
            <div class="form-group">
                <label for="password" class="custom-title-left">Password:</label>
                <input type="password" class="form-control custom-input-text" id="password" name="password" placeholder="Enter password"
                       maxlength="100">
            </div>
            <button type="submit" class="btn btn-default custom-button">Log In</button>
            <div class="margin-top custom-text-center">
                <a href="{% url 'signup' %}">Create new account</a>
            </div>
        </form>
    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/paginator.html
<ul class="pagination">
    {% if page.has_other_pages %}
        {% if page.has_previous %}
            <li><a href="?page={{ page.previous_page_number }}">«</a></li>
        {% endif %}
        {% for num in page.page_range_current %}
            {% if num == page.number %}
                <li class="active"><a>{{ num }}</a></li>
            {% else %}
                <li><a href="?page={{ num }}"> {{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <li><a href="?page={{ page.next_page_number }}">»</a>
            <li>
        {% endif %}
    {% endif %}
</ul>

1 sem/Web-technology/QuestionDay/templates/post_get_form.html
<html>
<body>
<p name='method_post'>Method: POST</p>
<form method='post' action='{% url 'post_get_view' %}'>
    {% csrf_token %}
    <p>Message: <input type='text' name='msg' value=''></p>
    <p><input type='submit' value='Submit'></p>
</form>
<br>
<p name='method_get'>Method: GET</p>
<form method='get' action='{% url 'post_get_view' %}'>
    <p>Message: <input type='text' name='q' value=''></p>
    <p><input type='submit' value='Submit'></p>
</form>

{% for x in data %}
    {{ x }}<br>
{% endfor %}

</body>
</html>

1 sem/Web-technology/QuestionDay/templates/question_item.html
<div class="row card">
    <div class="col-sm-3 margin-bottom">
        {% if question.user.avatar != '' %}
            <img src="/{{ question.user.avatar }}" width="100" height="100" class="img-circle"
                 alt="avatar">
        {% else %}
            <img src="/src/img/default_avatar.png" width="100" height="100" class="img-circle"
                 alt="avatar">
        {% endif %} 
    </div>
    <div class="col-sm-9 text-left">
        <a href="{% url 'question' question.id %}"><h3 class="custom-text-left no-margin-top">
            {{ question.title|truncatechars:50 }}</h3></a>
                <div>
            {% for tag in question.tag_list %}
                  <a href="{% url 'bytag' tag.name %}" class="custom-title-left tag">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <div>
            <h4 class="custom-text-left answer"><a href="{% url 'question' question.id %}">Answers ({{ question.answers_count }})</a>
            </h4>
        </div>
    </div>
</div>

1 sem/Web-technology/QuestionDay/templates/settings.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-left">
        <div class="div-align-left">
            <h2 class="custom-title-left text-inline-block">Settings:</h2>
            <h2 class="custom-text-left text-inline-block">Nickname</h2>
        </div>
        <form enctype="multipart/form-data" method="post" action="{% url 'settings' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email" class="custom-title-left">E-mail:</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_nickname" class="custom-title-left">NickName:</label>
                {{ form.nickname }}
            </div>

            {% if user.profile.avatar != '' %}
                <img src="/{{ user.profile.avatar }}" width="100" height="100" class="img-circle"
                     alt="avatar">
            {% else %}
                <img src="/src/img/default_avatar.png" width="100" height="100" class="img-circle"
                     alt="avatar">
            {% endif %}

            <div class="form-group">
                <label for="id_avatar" class="custom-title-left">Upload image:</label>
                {{ form.avatar }}
            </div>
            <button type="submit" class="btn btn-default custom-button">Save</button>
        </form>
    </div>
{% endblock %}

               

1 sem/Web-technology/QuestionDay/templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-left">
        <h2 class="custom-title-left">Sign Up</h2>
        {% for e in form.non_field_errors %}
            <h4 id="error-text" class="custom-text-left custom-text-error">{{ e }}</h4>
        {% endfor %}
        <form enctype="multipart/form-data" method="post" action="{% url 'signup' %}?continue={{ get }}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group {% if field.errors %}has-error {% endif %}">
                    <label class="custom-title-left">{{ field.label }}:</label>
                    {{ field }}
                </div>
                {% if field.errors %}<p class="help-block custom-text-left">{{ field.errors }}</p>{% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-default custom-button">Register</button>
        </form>
    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/signup_success.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-left">
        <h2 class="custom-title-center">Thank's for registration</h2>
        <a href="{% url 'login' %}" class="btn custom-button" role="button">Start right now</a>
    </div>
{% endblock %}

1 sem/Web-technology/QuestionDay/templates/tag.html
{% extends 'base.html' %}
{% block content %}
    <div class="div-align-left">
        <h2 class="custom-title-left text-inline-block">Tag:</h2>
        <h2 class="custom-text-left text-inline-block">{{ tag_name }}</h2>
    </div>
    <div class="container-fluid text-center">
        {% for question in questions %}
		{% include "question_item.html" %}		 
        {% endfor %}
    </div>
    {% include "paginator.html" %}
{% endblock %}